___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [9]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [10]:
np.ones((4,4),dtype=int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [11]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [12]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [14]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [20]:
np.linspace(0,24,25).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [21]:
np.random.rand(5)

array([0.50073927, 0.31671541, 0.27313746, 0.27327306, 0.29492613])

#### 11. Create random normal distributed 5x5 array

In [23]:
np.random.randn(25).reshape(5,5)

array([[-1.05888264, -0.51998193,  1.58636951, -0.18421116,  0.21377138],
       [-0.84960188,  0.9606671 , -0.15569635, -0.27791554,  1.35340648],
       [ 0.93795359, -0.02631243, -0.44210436,  0.29044745, -1.24663029],
       [ 1.26250607,  1.47914124, -1.62319918,  2.13124851, -1.06646943],
       [-1.91914927,  1.48235399,  0.17595862, -1.40238663,  0.2466929 ]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [38]:
list1=[np.random.randint(20,50) for x in range(12)]
np.array(list1).reshape(3,4)

array([[37, 44, 32, 24],
       [37, 49, 47, 41],
       [49, 29, 33, 33]])

#### 13. Reshape the array below with shape 6x8

In [40]:
ranarr = np.random.randint(0, 60, 48)
ranarr

array([19, 37, 45,  7, 27,  7, 10, 12, 55, 52,  5, 25,  6, 25, 50, 45, 35,
       47, 21,  4, 44,  6, 55, 56, 38,  4, 58, 41, 45, 12,  3, 47, 30, 37,
       18, 53,  4, 22, 17,  0, 46, 16, 50,  6, 13, 46, 54, 41])

In [41]:
ranarr.reshape(6,8)

array([[19, 37, 45,  7, 27,  7, 10, 12],
       [55, 52,  5, 25,  6, 25, 50, 45],
       [35, 47, 21,  4, 44,  6, 55, 56],
       [38,  4, 58, 41, 45, 12,  3, 47],
       [30, 37, 18, 53,  4, 22, 17,  0],
       [46, 16, 50,  6, 13, 46, 54, 41]])

In [42]:
#reshape with -1

## Numpy Indexing and Selection


In [45]:
#Create array below
my_arr = np.arange(1,17).reshape(4,4)
my_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [46]:
my_arr[[1,2],1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [50]:
my_arr[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [51]:
my_arr[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [84]:
my_arr[:,2]=77
my_arr

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [114]:
my_arr[(1,3),(0,2)]

array([ 5, 77])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [116]:
my_arr[1:4:2,0:3:2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [128]:
my_arr[my_arr<10]

array([1, 2, 4, 5, 6, 8, 9])

In [129]:
my_arr[my_arr>12]

array([77, 77, 77, 13, 14, 77, 16])

In [130]:
my_arr[my_arr<10]+my_arr[my_arr>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [131]:
np.std(my_arr[my_arr<10]+my_arr[my_arr>12])

29.700546274093877

#### 22. Get the sum of second column from array above

In [140]:
my_arr = np.array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])
my_arr

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [141]:
np.sum(my_arr[:,1])

32

#### 23. Get the median,mean and std of 3rd column from array above

In [145]:
#median
np.median(my_arr[:,3])

10.0

In [146]:
#mean
np.mean(my_arr[:,3])

10.0

In [153]:
#std
np.std(my_arr[:,3])

4.47213595499958

# Pandas Section

In [154]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [155]:
my_file = pd.read_csv('Salaries.csv')

In [158]:
my_file.head(5)

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [159]:
my_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
Id                  148654 non-null int64
EmployeeName        148654 non-null object
JobTitle            148654 non-null object
BasePay             148045 non-null float64
OvertimePay         148650 non-null float64
OtherPay            148650 non-null float64
Benefits            112491 non-null float64
TotalPay            148654 non-null float64
TotalPayBenefits    148654 non-null float64
Year                148654 non-null int64
Notes               0 non-null float64
Agency              148654 non-null object
Status              0 non-null float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [160]:
my_file.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year value are there**

In [164]:
my_file['Year'].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [165]:
#max
my_file['TotalPay'].max()

567595.43

In [169]:
#avg
my_file['TotalPay'].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [183]:
my_file[my_file['TotalPay']>my_file['TotalPay'].mean()].shape[0]

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [185]:
my_file['TotalPayBenefits'][my_file['EmployeeName']=='ALBERT PARDINI']

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [197]:
my_file['EmployeeName'][my_file['TotalPayBenefits'].idxmin()]

'Joe Lopez'

**What are the unique Jobs in dataset?**

In [189]:
my_file['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [192]:
my_file['JobTitle'].value_counts().tail(3)

Supervising Mediator, UFCS                            1
EXECUTIVE ASSISTANT TO THE GENERAL MANAGER, RETIRE    1
ASSISTANT RECREATION SUPERVISOR                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [195]:
my_file[my_file['TotalPayBenefits']>my_file['TotalPayBenefits'].mean()][my_file['Year']==2012].shape[0]

C:\Users\kd08uf\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


20366

**How many people have the word Manager in their job title?**

In [261]:
#use apply function here
def check(job):
    if 'manager' in job.lower():
        return True
    else:
        return False
    
my_file['Check'] = my_file['JobTitle'].apply(lambda x: check(x))
my_file[my_file['Check'] == True].shape[0]

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [275]:
sal_new = my_file.iloc[:,[0,1,2,7,8]]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [284]:
sal_new = my_file.loc[:,['EmployeeName','JobTitle','BasePay','OvertimePay','OtherPay','Benefits','TotalPay','TotalPayBenefits']]
sal_new

EmployeeName  \
0               NATHANIEL FORD   
1                 GARY JIMENEZ   
2               ALBERT PARDINI   
3            CHRISTOPHER CHONG   
4              PATRICK GARDNER   
5               DAVID SULLIVAN   
6                    ALSON LEE   
7                DAVID KUSHNER   
8               MICHAEL MORRIS   
9           JOANNE HAYES-WHITE   
10               ARTHUR KENNEY   
11            PATRICIA JACKSON   
12           EDWARD HARRINGTON   
13                 JOHN MARTIN   
14              DAVID FRANKLIN   
15             RICHARD CORRIEA   
16                    AMY HART   
17              SEBASTIAN WONG   
18                  MARTY ROSS   
19               ELLEN MOFFATT   
20                  VENUS AZAR   
21                JUDY MELINEK   
22               GEORGE GARCIA   
23               VICTOR WYRSCH   
24             JOSEPH DRISCOLL   
25                GREGORY SUHR   
26                 JOHN HANLEY   
27              RAYMOND GUZMAN   
28              DENISE SCHMITT   
29               MONICA FIELDS   
...                        ...   
148624      Lorraine Rosenthal   
148625         Renato C Gurion   
148626           Paulet Gaines   
148627        Brett A Lundberg   
148628          Mark W Mcclure   
148629       Elizabeth Iniguez   
148630            Randy J Keys   
148631         Andre M Johnson   
148632  Sharon D Owens-Webster   
148633        Edward Ferdinand   
148634          David M Turner   
148635     James S Kibblewhite   
148636           Andrew J Enzi   
148637        Kadeshra D Green   
148638    Lennard B Hutchinson   
148639       Richard A Talbert   
148640      Charlene D Mccully   
148641   Raphael Marquis Goins   
148642       Dominic C Marquez   
148643              Kim Brewer   
148644            Randy D Winn   
148645        Carolyn A Wilson   
148646            Not provided   
148647          Joann Anderson   
148648             Leon Walker   
148649           Roy I Tillery   
148650            Not provided   
148651            Not provided   
148652            Not provided   
148653               Joe Lopez   

                                                JobTitle    BasePay  \
0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                        CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                        CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
5                              ASSISTANT DEPUTY CHIEF II  118602.00   
6                     BATTALION CHIEF, (FIRE DEPARTMENT)   92492.01   
7                         DEPUTY DIRECTOR OF INVESTMENTS  256576.96   
8                     BATTALION CHIEF, (FIRE DEPARTMENT)  176932.64   
9                 CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)  285262.00   
10      ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)  194999.39   
11                       CAPTAIN III (POLICE DEPARTMENT)   99722.00   
12                           EXECUTIVE CONTRACT EMPLOYEE  294580.02   
13                                     DEPARTMENT HEAD V  271329.03   
14                    BATTALION CHIEF, (FIRE DEPARTMENT)  174872.64   
15                    COMMANDER III, (POLICE DEPARTMENT)  198778.01   
16                                     DEPARTMENT HEAD V  268604.57   
17                 CAPTAIN, EMERGENCYCY MEDICAL SERVICES  140546.87   
18                    BATTALION CHIEF, (FIRE DEPARTMENT)  168692.63   
19                            ASSISTANT MEDICAL EXAMINER  257510.59   
20                            ASSISTANT MEDICAL EXAMINER  257510.48   
21                            ASSISTANT MEDICAL EXAMINER  257510.44   
22                             CAPTAIN, FIRE SUPPRESSION  140546.88   
23                    BATTALION CHIEF, (FIRE DEPARTMENT)  168692.63   
24                             CAPTAIN, FIRE SUPPRESSION  140546.86   
25                                       CHIEF OF POLICE  25647

**Print out the names of the employees who earn more than min, but less than avg**

In [298]:
sal_new['EmployeeName'][(sal_new['TotalPayBenefits']>sal_new['TotalPayBenefits'].min()) & (sal_new['TotalPayBenefits']<sal_new['TotalPayBenefits'].mean())]

10806                     KWE LEE
10807              MIGUEL CARO JR
10808               JOANNE MORRIS
10809               LAYLA WELBORN
10810                     LE BANH
10811               OSCAR ROSALES
10812             KEITH DEMARTINI
10813     SONIA DELGADO-SCHAUMBER
10814                 ALBERT CHAN
10815            SUSHMA DHULIPALA
10816                  KINGMAN MA
10817                JIM DIMODICA
10818             RICHARD MORALES
10819               ROBERT RODRIN
10820               CURTIS TAYLOR
10821             HELEN VOZENILEK
10822        ALAN DELLA  MAGGIORA
10823              RANDY RADOVICH
10824                DANA KETCHAM
10825              JUSTIN CABULOY
10826                    YING YAN
10827           BARRY CHAMBERLAIN
10828              OSCAR COLLAZOS
10829                 SUSAN LEACH
10830              MICHAEL RIVERA
10831               DANIEL FICKER
10832                   PETER ONG
10833              ARTHUR JOHNSON
10834             JOSEPH SAN JUAN
10835         